DROP TABLE IF EXISTS acl_class CASCADE;
DROP TABLE IF EXISTS acl_entry CASCADE;
DROP TABLE IF EXISTS acl_object_identity CASCADE;
DROP TABLE IF EXISTS acl_sid CASCADE;

DROP TABLE IF EXISTS authority CASCADE;
DROP TABLE IF EXISTS journal CASCADE; 
DROP TABLE IF EXISTS researcher CASCADE;  
DROP TABLE IF EXISTS securityId CASCADE;  
